fix: remove row when no attributes are present
aemsites/devsite-runtime-connector pull request #25
Opened 2024-12-02 14:15 UTC by manimitrah

I found that a row was created when there were no attributes, so I added a condition to handle this.

**Before:**
![Screenshot 2024-12-02 192213](https://github.com/user-attachments/assets/fcc6c4d2-6eff-4795-a2ca-f979259c1640)

**After:**

![Screenshot 2024-12-02 193105](https://github.com/user-attachments/assets/e5632586-5f4f-45c2-8c44-463250d9b669)

2024-12-02 14:59 UTC, melissag-ensemble commented on src/steps/mdx-to-gridtables.ts
> +          ...(node.attributes && node.attributes.some(attr => attr.name !== "slots")
just curious, why are we destructuring here (...) when the expression already evaluates to a boolean?

2024-12-02 15:13 UTC, melissag-ensemble approved these changes

2024-12-04 18:00 UTC, melissag-ensemble requested changes
I think we can get rid of the if/else statement on `RedoclyAPIBlock` because we are now using a similar approach of adding each attribute on their own row.

There are some slight differences that might need to be consolidated, such as instead of storing attributes as `strong` `text`, we could probably just store them as `code` `text`.  Because `strong` makes sense to highlight the block name, but perhaps it's not necessary for attributes. Also `code` allows us to have special characters if needed (but also no harm for attribute values that don't have special characters).

You can test both scenarios with these urls:
- http://localhost:3000/app-builder/docs/overview/
- http://localhost:3000/github-actions-test/test/redocly-api-block

After making this connector change, we will both have to update `adp-devsite` but that'll be a good change cus then we only have to have one logic for consuming the attributes (rather than having one way for RedoclyAPIBlock, and another for the other blocks).

Please let me know what you think. I'm not sure if this is possible, just a suggestion to simplify our code.

2024-12-04 22:28 UTC, timkim approved these changes

2024-12-04 22:29 UTC, melissag-ensemble reviewed
On a related note, do we still need this: https://github.com/aemsites/devsite-runtime-connector/blob/main/src/steps/create-page-blocks.js#L104 (i.e. changes from this PR https://github.com/aemsites/devsite-runtime-connector/pull/17)?

If I remember correctly, these were used for adding attributes to the div (https://adobeio.slack.com/archives/C07FGR8VDU7/p1731610890547559?thread_ts=1731587238.252319&cid=C07FGR8VDU7). But now that we are adding them as rows, we don't need this anymore, right?

2024-12-04 22:29 UTC, merged